kind: Deployment
apiVersion: apps/v1
metadata:
  name: token-exchange-agent
  namespace: {{ .AddonInstallNamespace }}
  labels:
    app: token-exchange-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: token-exchange-agent
  template:
    metadata:
      labels:
        app: token-exchange-agent
    spec:
      serviceAccountName: token-exchange-agent-sa
      volumes:
      - name: hub-config
        secret:
          secretName: {{ .KubeConfigSecret }}
      containers:
      - name: token-exchange-agent
        image: {{ .Image }}
        imagePullPolicy: Always
        command:
        - "/manager"
        args:
          - "tokenexchange"
          - "--hub-kubeconfig=/var/run/hub/kubeconfig"
          - "--cluster-name={{ .ClusterName }}"
          - "--namespace={{ .AddonInstallNamespace }}"
        volumeMounts:
          - name: hub-config
            mountPath: /var/run/hub
