apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: odf-multicluster-orchestrator
  name: odfmo-appliedmanifest-admin-role
rules:
- apiGroups:
  - multicluster.odf.openshift.io
  resources:
  - appliedmanifests
  verbs:
  - '*'
- apiGroups:
  - multicluster.odf.openshift.io
  resources:
  - appliedmanifests/status
  verbs:
  - get
