apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: maintenance-agent-rolebinding
  namespace: {{ .AddonInstallNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: maintenance-agent-role
subjects:
- kind: ServiceAccount
  name: maintenance-agent-sa
  namespace: {{ .AddonInstallNamespace }}
