# This rule is not used by the project odf-multicluster-orchestrator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over multicluster.odf.openshift.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: odf-multicluster-orchestrator
    app.kubernetes.io/managed-by: kustomize
  name: appliedmanifest-admin-role
rules:
- apiGroups:
  - multicluster.odf.openshift.io
  resources:
  - appliedmanifests
  verbs:
  - '*'
- apiGroups:
  - multicluster.odf.openshift.io
  resources:
  - appliedmanifests/status
  verbs:
  - get
