## Append samples you want in your CSV to this file as resources ##
resources:
- multicluster_v1alpha1_mirrorpeer.yaml
- multicluster_v1alpha1_s3configuration.yaml
- multicluster_v1alpha1_sourcemanifest.yaml
- multicluster_v1alpha1_appliedmanifest.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
