apiVersion: multicluster.odf.openshift.io/v1alpha1
kind: MirrorPeer
metadata:
  name: mirrorpeer-sample
spec:
  storageVendor: odf
  type: async
  items:
    - clusterName: local-cluster
      storageClusterRef:
        name: ocs-storagecluster
        namespace: openshift-storage
    - clusterName: spoke-cluster
      storageClusterRef:
        name: ocs-storagecluster
        namespace: openshift-storage
