//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 Red Hat OpenShift Data Foundation.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorPeer) DeepCopyInto(out *MirrorPeer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorPeer.
func (in *MirrorPeer) DeepCopy() *MirrorPeer {
	if in == nil {
		return nil
	}
	out := new(MirrorPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MirrorPeer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorPeerList) DeepCopyInto(out *MirrorPeerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MirrorPeer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorPeerList.
func (in *MirrorPeerList) DeepCopy() *MirrorPeerList {
	if in == nil {
		return nil
	}
	out := new(MirrorPeerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MirrorPeerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorPeerSpec) DeepCopyInto(out *MirrorPeerSpec) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PeerRef, len(*in))
		copy(*out, *in)
	}
	if in.SchedulingIntervals != nil {
		in, out := &in.SchedulingIntervals, &out.SchedulingIntervals
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorPeerSpec.
func (in *MirrorPeerSpec) DeepCopy() *MirrorPeerSpec {
	if in == nil {
		return nil
	}
	out := new(MirrorPeerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorPeerStatus) DeepCopyInto(out *MirrorPeerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorPeerStatus.
func (in *MirrorPeerStatus) DeepCopy() *MirrorPeerStatus {
	if in == nil {
		return nil
	}
	out := new(MirrorPeerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerRef) DeepCopyInto(out *PeerRef) {
	*out = *in
	out.StorageClusterRef = in.StorageClusterRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerRef.
func (in *PeerRef) DeepCopy() *PeerRef {
	if in == nil {
		return nil
	}
	out := new(PeerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClusterRef) DeepCopyInto(out *StorageClusterRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClusterRef.
func (in *StorageClusterRef) DeepCopy() *StorageClusterRef {
	if in == nil {
		return nil
	}
	out := new(StorageClusterRef)
	in.DeepCopyInto(out)
	return out
}
