//go:build !ignore_autogenerated

/*
Copyright 2026 Red Hat Data Foundation.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationInfo) DeepCopyInto(out *ApplicationInfo) {
	*out = *in
	out.ApplicationRef = in.ApplicationRef
	if in.SubscriptionInfo != nil {
		in, out := &in.SubscriptionInfo, &out.SubscriptionInfo
		*out = new(SubscriptionInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationInfo.
func (in *ApplicationInfo) DeepCopy() *ApplicationInfo {
	if in == nil {
		return nil
	}
	out := new(ApplicationInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppliedManifest) DeepCopyInto(out *AppliedManifest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppliedManifest.
func (in *AppliedManifest) DeepCopy() *AppliedManifest {
	if in == nil {
		return nil
	}
	out := new(AppliedManifest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppliedManifest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppliedManifestList) DeepCopyInto(out *AppliedManifestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppliedManifest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppliedManifestList.
func (in *AppliedManifestList) DeepCopy() *AppliedManifestList {
	if in == nil {
		return nil
	}
	out := new(AppliedManifestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppliedManifestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppliedManifestSpec) DeepCopyInto(out *AppliedManifestSpec) {
	*out = *in
	if in.Manifests != nil {
		in, out := &in.Manifests, &out.Manifests
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppliedManifestSpec.
func (in *AppliedManifestSpec) DeepCopy() *AppliedManifestSpec {
	if in == nil {
		return nil
	}
	out := new(AppliedManifestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppliedManifestStatus) DeepCopyInto(out *AppliedManifestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppliedManifestStatus.
func (in *AppliedManifestStatus) DeepCopy() *AppliedManifestStatus {
	if in == nil {
		return nil
	}
	out := new(AppliedManifestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRInfo) DeepCopyInto(out *DRInfo) {
	*out = *in
	out.DRPolicyRef = in.DRPolicyRef
	if in.DRClusters != nil {
		in, out := &in.DRClusters, &out.DRClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProtectedNamespaces != nil {
		in, out := &in.ProtectedNamespaces, &out.ProtectedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRInfo.
func (in *DRInfo) DeepCopy() *DRInfo {
	if in == nil {
		return nil
	}
	out := new(DRInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DRStatusInfo) DeepCopyInto(out *DRStatusInfo) {
	*out = *in
	if in.LastGroupSyncTime != nil {
		in, out := &in.LastGroupSyncTime, &out.LastGroupSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DRStatusInfo.
func (in *DRStatusInfo) DeepCopy() *DRStatusInfo {
	if in == nil {
		return nil
	}
	out := new(DRStatusInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalS3Spec) DeepCopyInto(out *ExternalS3Spec) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalS3Spec.
func (in *ExternalS3Spec) DeepCopy() *ExternalS3Spec {
	if in == nil {
		return nil
	}
	out := new(ExternalS3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalS3Spec) DeepCopyInto(out *InternalS3Spec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalS3Spec.
func (in *InternalS3Spec) DeepCopy() *InternalS3Spec {
	if in == nil {
		return nil
	}
	out := new(InternalS3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorPeer) DeepCopyInto(out *MirrorPeer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorPeer.
func (in *MirrorPeer) DeepCopy() *MirrorPeer {
	if in == nil {
		return nil
	}
	out := new(MirrorPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MirrorPeer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorPeerList) DeepCopyInto(out *MirrorPeerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MirrorPeer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorPeerList.
func (in *MirrorPeerList) DeepCopy() *MirrorPeerList {
	if in == nil {
		return nil
	}
	out := new(MirrorPeerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MirrorPeerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorPeerSpec) DeepCopyInto(out *MirrorPeerSpec) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PeerRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorPeerSpec.
func (in *MirrorPeerSpec) DeepCopy() *MirrorPeerSpec {
	if in == nil {
		return nil
	}
	out := new(MirrorPeerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorPeerStatus) DeepCopyInto(out *MirrorPeerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorPeerStatus.
func (in *MirrorPeerStatus) DeepCopy() *MirrorPeerStatus {
	if in == nil {
		return nil
	}
	out := new(MirrorPeerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerRef) DeepCopyInto(out *PeerRef) {
	*out = *in
	out.StorageClusterRef = in.StorageClusterRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerRef.
func (in *PeerRef) DeepCopy() *PeerRef {
	if in == nil {
		return nil
	}
	out := new(PeerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementInfo) DeepCopyInto(out *PlacementInfo) {
	*out = *in
	out.PlacementRef = in.PlacementRef
	if in.SelectedClusters != nil {
		in, out := &in.SelectedClusters, &out.SelectedClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementInfo.
func (in *PlacementInfo) DeepCopy() *PlacementInfo {
	if in == nil {
		return nil
	}
	out := new(PlacementInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectedApplicationView) DeepCopyInto(out *ProtectedApplicationView) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectedApplicationView.
func (in *ProtectedApplicationView) DeepCopy() *ProtectedApplicationView {
	if in == nil {
		return nil
	}
	out := new(ProtectedApplicationView)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProtectedApplicationView) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectedApplicationViewList) DeepCopyInto(out *ProtectedApplicationViewList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProtectedApplicationView, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectedApplicationViewList.
func (in *ProtectedApplicationViewList) DeepCopy() *ProtectedApplicationViewList {
	if in == nil {
		return nil
	}
	out := new(ProtectedApplicationViewList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProtectedApplicationViewList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectedApplicationViewSpec) DeepCopyInto(out *ProtectedApplicationViewSpec) {
	*out = *in
	out.DRPCRef = in.DRPCRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectedApplicationViewSpec.
func (in *ProtectedApplicationViewSpec) DeepCopy() *ProtectedApplicationViewSpec {
	if in == nil {
		return nil
	}
	out := new(ProtectedApplicationViewSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectedApplicationViewStatus) DeepCopyInto(out *ProtectedApplicationViewStatus) {
	*out = *in
	in.ApplicationInfo.DeepCopyInto(&out.ApplicationInfo)
	if in.PlacementInfo != nil {
		in, out := &in.PlacementInfo, &out.PlacementInfo
		*out = new(PlacementInfo)
		(*in).DeepCopyInto(*out)
	}
	in.DRInfo.DeepCopyInto(&out.DRInfo)
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectedApplicationViewStatus.
func (in *ProtectedApplicationViewStatus) DeepCopy() *ProtectedApplicationViewStatus {
	if in == nil {
		return nil
	}
	out := new(ProtectedApplicationViewStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Configuration) DeepCopyInto(out *S3Configuration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Configuration.
func (in *S3Configuration) DeepCopy() *S3Configuration {
	if in == nil {
		return nil
	}
	out := new(S3Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *S3Configuration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3ConfigurationList) DeepCopyInto(out *S3ConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]S3Configuration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3ConfigurationList.
func (in *S3ConfigurationList) DeepCopy() *S3ConfigurationList {
	if in == nil {
		return nil
	}
	out := new(S3ConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *S3ConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3ConfigurationSpec) DeepCopyInto(out *S3ConfigurationSpec) {
	*out = *in
	if in.InternalS3 != nil {
		in, out := &in.InternalS3, &out.InternalS3
		*out = new(InternalS3Spec)
		**out = **in
	}
	if in.ExternalS3 != nil {
		in, out := &in.ExternalS3, &out.ExternalS3
		*out = new(ExternalS3Spec)
		**out = **in
	}
	if in.ManagedClusters != nil {
		in, out := &in.ManagedClusters, &out.ManagedClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3ConfigurationSpec.
func (in *S3ConfigurationSpec) DeepCopy() *S3ConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(S3ConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3ConfigurationStatus) DeepCopyInto(out *S3ConfigurationStatus) {
	*out = *in
	if in.ConfiguredClusters != nil {
		in, out := &in.ConfiguredClusters, &out.ConfiguredClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3ConfigurationStatus.
func (in *S3ConfigurationStatus) DeepCopy() *S3ConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(S3ConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceManifest) DeepCopyInto(out *SourceManifest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceManifest.
func (in *SourceManifest) DeepCopy() *SourceManifest {
	if in == nil {
		return nil
	}
	out := new(SourceManifest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SourceManifest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceManifestList) DeepCopyInto(out *SourceManifestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SourceManifest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceManifestList.
func (in *SourceManifestList) DeepCopy() *SourceManifestList {
	if in == nil {
		return nil
	}
	out := new(SourceManifestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SourceManifestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceManifestSpec) DeepCopyInto(out *SourceManifestSpec) {
	*out = *in
	if in.Manifests != nil {
		in, out := &in.Manifests, &out.Manifests
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceManifestSpec.
func (in *SourceManifestSpec) DeepCopy() *SourceManifestSpec {
	if in == nil {
		return nil
	}
	out := new(SourceManifestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceManifestStatus) DeepCopyInto(out *SourceManifestStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceManifestStatus.
func (in *SourceManifestStatus) DeepCopy() *SourceManifestStatus {
	if in == nil {
		return nil
	}
	out := new(SourceManifestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClusterRef) DeepCopyInto(out *StorageClusterRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClusterRef.
func (in *StorageClusterRef) DeepCopy() *StorageClusterRef {
	if in == nil {
		return nil
	}
	out := new(StorageClusterRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionInfo) DeepCopyInto(out *SubscriptionInfo) {
	*out = *in
	if in.SubscriptionRefs != nil {
		in, out := &in.SubscriptionRefs, &out.SubscriptionRefs
		*out = make([]corev1.ObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionInfo.
func (in *SubscriptionInfo) DeepCopy() *SubscriptionInfo {
	if in == nil {
		return nil
	}
	out := new(SubscriptionInfo)
	in.DeepCopyInto(out)
	return out
}
