apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: token-exchange-agent-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update"]
  resourceName: "odf-info"
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["objectbucket.io"]
  resources: ["objectbucketclaims"]
  verbs: ["get", "list", "watch", "create", "delete","update"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get","list","update"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshotclasses"]
  verbs: ["get", "list","update"]
- apiGroups: ["ocs.openshift.io"]
  resources: ["storageconsumers", "storageclusters"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["template.openshift.io"]
  resources: ["templates"]
  verbs: ["get", "list", "watch"]
  