apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: token-exchange-agent-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["ceph.rook.io"]
  resources: ["cephclusters"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["ocs.openshift.io"]
  resources: ["storageclusters"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["objectbucket.io"]
  resources: ["objectbucketclaims"]
  verbs: ["get", "create", "list", "watch", "delete"]
- apiGroups: ["multicluster.odf.openshift.io"]
  resources: ["mirrorpeers"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get","list","update"]
- apiGroups: ["submariner.io"]
  resources: ["submariners"]
  verbs: ["get"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["replicasets", "deployments"]
  verbs: ["get","update","list","watch"]
- apiGroups: ["ramendr.openshift.io"]
  resources: ["maintenancemodes","maintenancemodes/status"]
  verbs: ["get", "list","watch","update", "patch"]
