kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: token-exchange-agent-role
  namespace: {{ .AddonInstallNamespace }}
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["replicasets", "deployments"]
  verbs: ["get"]
- apiGroups: ["", "events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["ceph.rook.io"]
  resources: ["cephclusters"]
  verbs: ["get", "list", "update"]
- apiGroups: ["ocs.openshift.io"]
  resources: ["storageclusters"]
  verbs: ["get", "watch", "list", "create", "update"]
- apiGroups: ["template.openshift.io"]
  resources: ["templates", "templates/finalizer"]
  verbs: ["update"]
