kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: token-exchange-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: token-exchange-agent-role
subjects:
- kind: ServiceAccount
  name: token-exchange-agent-sa
  namespace: {{ .AddonInstallNamespace }}
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: {{ .User }}
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: {{ .Group }}