apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:token-exchange:agent
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["multicluster.odf.openshift.io"]
  resources: ["mirrorpeers"]
  verbs: ["get", "list", "watch", "update"]