kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open-cluster-management:token-exchange:agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:token-exchange:agent
subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: {{ .User }}
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: {{ .Group }}